export const sample = `- app : feed text app
  - browser
  - mail
  - rss
  - twitter
  - tumblr
  - front : front vue
    - tmbr
  - pipe : pipedream apis
    - mail_parser : mail parser
    - pipe_items : items
    - action
    - fetcher
  - mongo : mongodb
    - mongo_items : items
    - sources
    - label_category : label category
  - browser -> tmbr
  - tmbr -> action
  - pipe_items -> tmbr
  - mail -> mail_parser
  - mail_parser -> mongo_items
  - mongo_items->pipe_items
  - action -> twitter
  - action-> tumblr
  - action -> label_category
  - rss -> fetcher
  - twitter -> fetcher
  - tumblr -> fetcher
  - fetcher -> mongo_items
  - sources -> fetcher : target and \\n when to retrieve
  - fetcher -> sources : time \\n to fetched
`
